version: "3.9"  # optional since v1.27.0
services:
  frontend:   
    image:  si3mshady/popularlanguages-fe:1
    ports:
      - "888:80"
   
  api:   
    image:  si3mshady/popularlanguages:3
    ports:
      - "8000:8000"
   
  db:
    volumes:
      - jobdata:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"       
volumes:
  jobdata: